apiVersion: v1
kind: Pod
metadata:
  name: dongjak-hu1
  namespace: vicsnet
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-flat-14", "namespace": "default", "ips": ["192.168.14.103"]}
    ]'
spec:
  containers:
  - name: dongjak-hu1
    image: 192.168.103.250:5000/nfd_grpc_base:1.2
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'dongjak_hu1'
    - name: vICSNF_MGMTIP
      value: '127.0.0.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/seoul\\/dongjak\\/h\\/hu1'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'dongjak_h'
    - name: vICSNF_NEIGHBOR_IP
      value: '192.168.14.102'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea\\/seoul\\/dongjak\\/h#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/seoul\\/dongjak\\/hospital\\/unit1:korea\\/seoul\\/dongjak\\/hospital\\/ng\\/unit1:korea\\/incidents\\/01\\/HT\\/h\\/G1'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      ## is nlsr daemon start
      value: 'NO'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "service ssh restart; /root/start_vicsnf.sh; sleep 1d"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-mec1
