apiVersion: v1
kind: Pod
metadata:
  name: c-vnf
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.221"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "public-subnet", "namespace": "default", "ips": ["192.168.100.221"]}
    ]'
spec:
  containers:
  - name: c-vnf
    image: 192.168.103.250:5000/ndn_dtn_base_vnc-0.6.5:1.0
    ## For vnc, it must be disabled
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'c-vnf'
    - name: vICSNF_MGMTIP
      value: '127.0.0.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'c-vnf'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'vm-vnf'
    - name: vICSNF_NEIGHBOR_IP
      value: '192.168.100.222'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'vm-vnf#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'container\\/headquarter'
    - name: vNLSR_LIFETIME
      value: '60000'
    - name: vNLSR_HELLOTIME
      value: '40'
    - name: vNLSR_FIRST_HELLOTIME
      value: '10'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'YES'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    - name: VNC_PW
      value: vicsnf
    livenessProbe:
      tcpSocket:
        port: 5901
      initialDelaySeconds: 1
      timeoutSeconds: 1
    ### checks if http-vnc connection is working
    readinessProbe:
      httpGet:
        path: /
        port: 6901
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 1
    securityContext:
      privileged: true
      runAsUser: 0
      #runAsGroup: 0
    command: ["/bin/bash", "-c", "service ssh restart; /root/start_vicsnf.sh; /dockerstartup/vnc_startup.sh --wait;"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-edge1
