apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kuryr-ndn-11
  annotations:
    openstack.org/kuryr-config: '{"subnetId": "bc433b16-015b-4448-800b-028d88b70ec1"}'
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "kuryr-cni",
    "name": "kuryr",
    "kuryr_conf": "/etc/kuryr/kuryr.conf",
    "debug": false
  }'
