apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kuryr-ndn-98
  annotations:
    openstack.org/kuryr-config: '{"subnetId": "1fa4ac91-52f0-4472-aca8-86cec3125cae"}'
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "kuryr-cni",
    "name": "kuryr",
    "kuryr_conf": "/etc/kuryr/kuryr.conf",
    "debug": false
  }'
