apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kuryr-ndn-97
  annotations:
    openstack.org/kuryr-config: '{"subnetId": "17254eaa-a902-47bf-ac40-6a99d1d6a54a"}'
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "kuryr-cni",
    "name": "kuryr",
    "kuryr_conf": "/etc/kuryr/kuryr.conf",
    "debug": false
  }'
