apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: kuryr-ndn-20
  annotations:
    openstack.org/kuryr-config: '{"subnetId": "1c731069-745b-4c9e-98ed-cbe69fa97a23"}'
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "type": "kuryr-cni",
    "name": "kuryr",
    "kuryr_conf": "/etc/kuryr/kuryr.conf",
    "debug": false
  }'
