apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: public-subnet
  annotations:
    openstack.org/kuryr-config: '{"subnetId": "7d3c3425-5dca-43ca-a3c0-66a1317baa1b"}'
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "kuryr-cni",
    "name": "kuryr",
    "kuryr_conf": "/etc/kuryr/kuryr.conf",
    "debug": false
  }'
