apiVersion: v1
kind: Pod
metadata:
  name: dongjak
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.110"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-10", "namespace": "default", "ips": ["10.10.10.101"]},
      {"name": "kuryr-ndn-20", "namespace": "default", "ips": ["10.10.20.110"]},
      {"name": "kuryr-ndn-13", "namespace": "default", "ips": ["10.10.13.101"]},
      {"name": "kuryr-ndn-14", "namespace": "default", "ips": ["10.10.14.101"]}
    ]'
spec:
  containers:
  - name: dongjak
    image: 192.168.103.250:5000/ndn_dtn_base-0.6.5:0.9
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'dongjak'
    - name: vICSNF_MGMTIP
      value: '127.0.0.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/seoul\\/dongjak'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'seoul:gangnam:dongjak-pf:dongjak-h'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.10.100:10.10.20.111:10.10.13.102:10.10.14.102'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea\\/seoul#R1:korea\\/seoul\\/gangnam#R1:korea\\/seoul\\/dongjak\\/pf#R1:korea\\/seoul\\/dongjak\\/h#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/seoul\\/dongjak:korea\\/incidents\\/01\\/HT'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'NO'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "service ssh restart; /root/start_vicsnf.sh; sleep 1d"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-edge1
