apiVersion: v1
kind: Pod
metadata:
  name: dongjak-mule
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.106"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-99", "namespace": "default", "ips": ["10.10.99.97"]},
      {"name": "kuryr-ndn-13", "namespace": "default", "ips": ["10.10.13.97"]},
      {"name": "kuryr-ndn-14", "namespace": "default", "ips": ["10.10.14.97"]}
    ]'
spec:
  containers:
  - name: dongjak-mule
    image: 192.168.103.250:5000/icn-dtn-base-0.6.5:1.0
    ## For vnc, it must be disabled
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'dongjak-mule'
    - name: vICSNF_MGMTIP
      value: '127.10.10.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/seoul\\/dongjak\\/mule'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'korea:dongjak-pf:dongjak-h'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.99.99:10.10.13.102:10.10.14.102'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea#R1:korea\\/seoul\\/dongjak\\/pf#R1:korea\\/seoul\\/dongjak\\/h#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/seoul\\/dongjak\\/mule'
    - name: vNLSR_LIFETIME
      value: '60000'
    - name: vNLSR_HELLOTIME
      value: '40'
    - name: vNLSR_FIRST_HELLOTIME
      value: '10'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'NO'
    - name: vDTN_SUPPORT
      value: 'YES'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0:lan1:lan2'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1:tcp#eth2:tcp#eth3'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "/root/start_vicsnf.sh; sleep 1d;"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-core2
