apiVersion: v1
kind: Pod
metadata:
  name: gangnam
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.111"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-11", "namespace": "default", "ips": ["10.10.11.101"]},
      {"name": "kuryr-ndn-20", "namespace": "default", "ips": ["10.10.20.111"]},
      {"name": "kuryr-ndn-15", "namespace": "default", "ips": ["10.10.15.101"]},
      {"name": "kuryr-ndn-16", "namespace": "default", "ips": ["10.10.16.101"]}
    ]'
spec:
  containers:
  - name: gangnam
    image: 192.168.103.250:5000/ndn_dtn_base-0.6.5:0.9
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'gangnam'
    - name: vICSNF_MGMTIP
      value: '127.0.0.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/seoul\\/gangnam'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'seoul:dongjak:gangnam-pf:gangnam-h'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.11.100:10.10.20.110:10.10.15.102:10.10.16.102'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea\\/seoul#R1:korea\\/seoul\\/dongjak#R1:korea\\/seoul\\/gangnam\\/pf#R1:korea\\/seoul\\/gangnam\\/h#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/seoul\\/gangnam:korea\\/incidents\\/01\\/PT:korea\\/incidents\\/01\\/FT'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'NO'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "service ssh restart; /root/start_vicsnf.sh; sleep 1d"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-edge2
