apiVersion: v1
kind: Pod
metadata:
  name: gyeonggi
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.112"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-98", "namespace": "default", "ips": ["10.10.98.100"]},
      {"name": "kuryr-ndn-12", "namespace": "default", "ips": ["10.10.12.100"]}
    ]'
spec:
  containers:
  - name: gyeonggi
    image: 192.168.103.250:5000/icn-dtn-base-0.6.5:1.0
    ## For vnc, it must be disabled
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'gyeonggi'
    - name: vICSNF_MGMTIP
      value: '127.10.10.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/gyeonggi'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'korea:seongnam'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.98.99:10.10.12.101'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea#R1:korea\\/gyeonggi\\/seongnam#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/gyeonggi'
    - name: vNLSR_LIFETIME
      value: '60000'
    - name: vNLSR_HELLOTIME
      value: '40'
    - name: vNLSR_FIRST_HELLOTIME
      value: '10'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'NO'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "/root/start_vicsnf.sh; sleep 1d;"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-core2
