apiVersion: v1
kind: Pod
metadata:
  name: korea
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.108"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-99", "namespace": "default", "ips": ["10.10.99.99"]},
      {"name": "kuryr-ndn-98", "namespace": "default", "ips": ["10.10.98.99"]},
      {"name": "kuryr-ndn-97", "namespace": "default", "ips": ["10.10.97.99"]}
    ]'
spec:
  containers:
  - name: korea
    image: 192.168.103.250:5000/icn-dtn-base-0.6.5:1.0
    ## For vnc, it must be disabled
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'korea'
    - name: vICSNF_MGMTIP
      value: '127.10.10.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'seoul:gyeonggi:korea-hq'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.99.100:10.10.98.100:10.10.97.98'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea\\/seoul#R1:korea\\/gyeonggi#R1:korea\\/hq#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea:korea\\/incidents'
    - name: vNLSR_LIFETIME
      value: '60000'
    - name: vNLSR_HELLOTIME
      value: '60'
    - name: vNLSR_FIRST_HELLOTIME
      value: '10'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'YES'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "/root/start_vicsnf.sh; sleep 30d;"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-core1
