apiVersion: v1
kind: Pod
metadata:
  name: seongnam
  namespace: vicsnet
  annotations:
    default_ip: "10.10.9.117"
    k8s.v1.cni.cncf.io/networks: '[
      {"name": "kuryr-ndn-12", "namespace": "default", "ips": ["10.10.12.101"]},
      {"name": "kuryr-ndn-17", "namespace": "default", "ips": ["10.10.17.101"]}
    ]'
spec:
  containers:
  - name: seongnam
    image: 192.168.103.250:5000/icn-dtn-base-0.6.5:1.0
    workingDir: /root
    env:
    - name: LC_ALL
      value: C.UTF-8
    - name: vICSNF_ALIAS
      value: 'seongnam'
    - name: vICSNF_MGMTIP
      value: '127.10.10.1'
    - name: vICSNF_MGMTPORT
      value: '50051'
    - name: vICSNF_SITENAME
      value: 'korea\\/gyeonggi\\/seongnam'
    - name: vICSNF_ROUTERNAME
      value: 'R1'
    - name: vICSNF_NEIGHBOR_HOSTNAME
      value: 'gyeonggi:seongnam-pfh'
    - name: vICSNF_NEIGHBOR_IP
      value: '10.10.12.100:10.10.17.102'
    - name: vICSNF_NEIGHBOR_SITE_ROUTE
      # SITE_NAME#ROUTE_NAME:N:N
      value: 'korea\\/gyeonggi#R1:korea\\/gyeonggi\\/seongnam\\/pfh#R1'
    - name: vICSNF_AD_PREFIXE
      value: 'korea\\/gyeonggi\\/seongnam'
    - name: vNLSR_LIFETIME
      value: '60000'
    - name: vNLSR_HELLOTIME
      value: '60'
    - name: vNLSR_FIRST_HELLOTIME
      value: '10'
    - name: vICSNF_ENV_CHANGE
      value: 'NO'
    - name: vICSNF_IS_START
      value: 'YES'
    - name: vDTN_SUPPORT
      value: 'NO'
    - name: vCONVERGENCE_INTERFACES
      value: 'lan0'
    - name: vCONVERGENCE_LAYER
      value: 'tcp#eth1'
    - name: vDTN_DEFAULT_PREFIX
      value: '\\/nfd'
    securityContext:
      privileged: true
    command: ["/bin/bash", "-c", "/root/start_vicsnf.sh; sleep 30d"]
  nodeSelector:
    kubernetes.io/hostname: vicsnet-edge2
